// US & Canada city coordinate database
// Fields: city / state / country / latitude / longitude / timezone (IANA) / tzOffset (standard UTC offset, hours)

export interface CityCoordinate {
  city: string;
  state: string;
  country: 'US' | 'CA';
  latitude: number;
  longitude: number;
  timezone: string;
  tzOffset: number;
}

export const cityList: CityCoordinate[] = [
  // ===== United States - Major cities =====
  { city: 'New York', state: 'NY', country: 'US', latitude: 40.7128, longitude: -74.006, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Los Angeles', state: 'CA', country: 'US', latitude: 34.0522, longitude: -118.2437, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Chicago', state: 'IL', country: 'US', latitude: 41.8781, longitude: -87.6298, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Houston', state: 'TX', country: 'US', latitude: 29.7604, longitude: -95.3698, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Phoenix', state: 'AZ', country: 'US', latitude: 33.4484, longitude: -112.074, timezone: 'America/Phoenix', tzOffset: -7 },
  { city: 'Philadelphia', state: 'PA', country: 'US', latitude: 39.9526, longitude: -75.1652, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'San Antonio', state: 'TX', country: 'US', latitude: 29.4241, longitude: -98.4936, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'San Diego', state: 'CA', country: 'US', latitude: 32.7157, longitude: -117.1611, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Dallas', state: 'TX', country: 'US', latitude: 32.7767, longitude: -96.797, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'San Jose', state: 'CA', country: 'US', latitude: 37.3382, longitude: -121.8863, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Austin', state: 'TX', country: 'US', latitude: 30.2672, longitude: -97.7431, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Jacksonville', state: 'FL', country: 'US', latitude: 30.3322, longitude: -81.6557, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Fort Worth', state: 'TX', country: 'US', latitude: 32.7555, longitude: -97.3308, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Columbus', state: 'OH', country: 'US', latitude: 39.9612, longitude: -82.9988, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Charlotte', state: 'NC', country: 'US', latitude: 35.2271, longitude: -80.8431, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'San Francisco', state: 'CA', country: 'US', latitude: 37.7749, longitude: -122.4194, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Indianapolis', state: 'IN', country: 'US', latitude: 39.7684, longitude: -86.1581, timezone: 'America/Indiana/Indianapolis', tzOffset: -5 },
  { city: 'Seattle', state: 'WA', country: 'US', latitude: 47.6062, longitude: -122.3321, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Denver', state: 'CO', country: 'US', latitude: 39.7392, longitude: -104.9903, timezone: 'America/Denver', tzOffset: -7 },
  { city: 'Washington', state: 'DC', country: 'US', latitude: 38.9072, longitude: -77.0369, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Boston', state: 'MA', country: 'US', latitude: 42.3601, longitude: -71.0589, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Nashville', state: 'TN', country: 'US', latitude: 36.1627, longitude: -86.7816, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Baltimore', state: 'MD', country: 'US', latitude: 39.2904, longitude: -76.6122, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Oklahoma City', state: 'OK', country: 'US', latitude: 35.4676, longitude: -97.5164, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Portland', state: 'OR', country: 'US', latitude: 45.5152, longitude: -122.6784, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Las Vegas', state: 'NV', country: 'US', latitude: 36.1699, longitude: -115.1398, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Memphis', state: 'TN', country: 'US', latitude: 35.1495, longitude: -90.049, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Louisville', state: 'KY', country: 'US', latitude: 38.2527, longitude: -85.7585, timezone: 'America/Kentucky/Louisville', tzOffset: -5 },
  { city: 'Milwaukee', state: 'WI', country: 'US', latitude: 43.0389, longitude: -87.9065, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Albuquerque', state: 'NM', country: 'US', latitude: 35.0844, longitude: -106.6504, timezone: 'America/Denver', tzOffset: -7 },
  { city: 'Tucson', state: 'AZ', country: 'US', latitude: 32.2226, longitude: -110.9747, timezone: 'America/Phoenix', tzOffset: -7 },
  { city: 'Fresno', state: 'CA', country: 'US', latitude: 36.7378, longitude: -119.7871, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Sacramento', state: 'CA', country: 'US', latitude: 38.5816, longitude: -121.4944, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Kansas City', state: 'MO', country: 'US', latitude: 39.0997, longitude: -94.5786, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Mesa', state: 'AZ', country: 'US', latitude: 33.4152, longitude: -111.8315, timezone: 'America/Phoenix', tzOffset: -7 },
  { city: 'Atlanta', state: 'GA', country: 'US', latitude: 33.749, longitude: -84.388, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Omaha', state: 'NE', country: 'US', latitude: 41.2565, longitude: -95.9345, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Colorado Springs', state: 'CO', country: 'US', latitude: 38.8339, longitude: -104.8214, timezone: 'America/Denver', tzOffset: -7 },
  { city: 'Raleigh', state: 'NC', country: 'US', latitude: 35.7796, longitude: -78.6382, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Miami', state: 'FL', country: 'US', latitude: 25.7617, longitude: -80.1918, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Long Beach', state: 'CA', country: 'US', latitude: 33.7701, longitude: -118.1937, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Virginia Beach', state: 'VA', country: 'US', latitude: 36.8529, longitude: -75.99, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Oakland', state: 'CA', country: 'US', latitude: 37.8044, longitude: -122.2712, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Minneapolis', state: 'MN', country: 'US', latitude: 44.9778, longitude: -93.265, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Arlington', state: 'TX', country: 'US', latitude: 32.7357, longitude: -97.1081, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Tampa', state: 'FL', country: 'US', latitude: 27.9506, longitude: -82.4572, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'New Orleans', state: 'LA', country: 'US', latitude: 29.9511, longitude: -90.0715, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Wichita', state: 'KS', country: 'US', latitude: 37.6876, longitude: -97.3301, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Cleveland', state: 'OH', country: 'US', latitude: 41.4993, longitude: -81.6944, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Bakersfield', state: 'CA', country: 'US', latitude: 35.3733, longitude: -119.0187, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Aurora', state: 'CO', country: 'US', latitude: 39.7294, longitude: -104.8319, timezone: 'America/Denver', tzOffset: -7 },
  { city: 'Anaheim', state: 'CA', country: 'US', latitude: 33.8366, longitude: -117.9143, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Honolulu', state: 'HI', country: 'US', latitude: 21.3069, longitude: -157.8583, timezone: 'Pacific/Honolulu', tzOffset: -10 },
  { city: 'Santa Ana', state: 'CA', country: 'US', latitude: 33.7455, longitude: -117.8677, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Riverside', state: 'CA', country: 'US', latitude: 33.9533, longitude: -117.3962, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Corpus Christi', state: 'TX', country: 'US', latitude: 27.8006, longitude: -97.3963, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Lexington', state: 'KY', country: 'US', latitude: 38.0406, longitude: -84.5037, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Stockton', state: 'CA', country: 'US', latitude: 37.9577, longitude: -121.2908, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'St. Louis', state: 'MO', country: 'US', latitude: 38.627, longitude: -90.1994, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Saint Paul', state: 'MN', country: 'US', latitude: 44.9537, longitude: -93.09, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Henderson', state: 'NV', country: 'US', latitude: 36.0397, longitude: -114.0231, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Pittsburgh', state: 'PA', country: 'US', latitude: 40.4406, longitude: -79.9959, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Cincinnati', state: 'OH', country: 'US', latitude: 39.1031, longitude: -84.512, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Newark', state: 'NJ', country: 'US', latitude: 40.7357, longitude: -74.1724, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Orlando', state: 'FL', country: 'US', latitude: 28.5383, longitude: -81.3792, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Salt Lake City', state: 'UT', country: 'US', latitude: 40.7608, longitude: -111.891, timezone: 'America/Denver', tzOffset: -7 },
  { city: 'Birmingham', state: 'AL', country: 'US', latitude: 33.5186, longitude: -86.8104, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Buffalo', state: 'NY', country: 'US', latitude: 42.8864, longitude: -78.8784, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Jersey City', state: 'NJ', country: 'US', latitude: 40.7178, longitude: -74.0431, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Detroit', state: 'MI', country: 'US', latitude: 42.3314, longitude: -83.0458, timezone: 'America/Detroit', tzOffset: -5 },
  { city: 'Richmond', state: 'VA', country: 'US', latitude: 37.5407, longitude: -77.436, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Hartford', state: 'CT', country: 'US', latitude: 41.7658, longitude: -72.6734, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Providence', state: 'RI', country: 'US', latitude: 41.824, longitude: -71.4128, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Des Moines', state: 'IA', country: 'US', latitude: 41.5868, longitude: -93.625, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Anchorage', state: 'AK', country: 'US', latitude: 61.2181, longitude: -149.9003, timezone: 'America/Anchorage', tzOffset: -9 },
  { city: 'Little Rock', state: 'AR', country: 'US', latitude: 34.7465, longitude: -92.2896, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Boise', state: 'ID', country: 'US', latitude: 43.615, longitude: -116.2023, timezone: 'America/Boise', tzOffset: -7 },
  { city: 'Burlington', state: 'VT', country: 'US', latitude: 44.4759, longitude: -73.2121, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Cheyenne', state: 'WY', country: 'US', latitude: 41.14, longitude: -104.8202, timezone: 'America/Denver', tzOffset: -7 },
  { city: 'Wilmington', state: 'DE', country: 'US', latitude: 39.7391, longitude: -75.5398, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Fargo', state: 'ND', country: 'US', latitude: 46.8772, longitude: -96.7898, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Sioux Falls', state: 'SD', country: 'US', latitude: 43.551, longitude: -96.7003, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Billings', state: 'MT', country: 'US', latitude: 45.7833, longitude: -108.5007, timezone: 'America/Denver', tzOffset: -7 },
  { city: 'Casper', state: 'WY', country: 'US', latitude: 42.8666, longitude: -106.3131, timezone: 'America/Denver', tzOffset: -7 },
  { city: 'Manchester', state: 'NH', country: 'US', latitude: 42.9956, longitude: -71.4548, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Portland', state: 'ME', country: 'US', latitude: 43.6591, longitude: -70.2568, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Bangor', state: 'ME', country: 'US', latitude: 44.8018, longitude: -68.7709, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Charleston', state: 'WV', country: 'US', latitude: 38.3498, longitude: -81.6326, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Jackson', state: 'MS', country: 'US', latitude: 32.2988, longitude: -90.1845, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Montgomery', state: 'AL', country: 'US', latitude: 32.3792, longitude: -86.3077, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Juneau', state: 'AK', country: 'US', latitude: 58.3019, longitude: -134.4197, timezone: 'America/Juneau', tzOffset: -9 },
  { city: 'Salem', state: 'OR', country: 'US', latitude: 44.9429, longitude: -123.0351, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Olympia', state: 'WA', country: 'US', latitude: 47.0379, longitude: -122.9007, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Carson City', state: 'NV', country: 'US', latitude: 39.1638, longitude: -119.7674, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Santa Fe', state: 'NM', country: 'US', latitude: 35.687, longitude: -105.9378, timezone: 'America/Denver', tzOffset: -7 },
  { city: 'Topeka', state: 'KS', country: 'US', latitude: 39.0489, longitude: -95.678, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Lincoln', state: 'NE', country: 'US', latitude: 40.8136, longitude: -96.7026, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Madison', state: 'WI', country: 'US', latitude: 43.0731, longitude: -89.4012, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Springfield', state: 'IL', country: 'US', latitude: 39.7817, longitude: -89.6501, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Frankfort', state: 'KY', country: 'US', latitude: 38.2009, longitude: -84.8733, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Tallahassee', state: 'FL', country: 'US', latitude: 30.4383, longitude: -84.2807, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Columbia', state: 'SC', country: 'US', latitude: 34.0007, longitude: -81.0348, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Dover', state: 'DE', country: 'US', latitude: 39.1582, longitude: -75.524, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Trenton', state: 'NJ', country: 'US', latitude: 40.2206, longitude: -74.7597, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Albany', state: 'NY', country: 'US', latitude: 42.6526, longitude: -73.7562, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Concord', state: 'NH', country: 'US', latitude: 43.2081, longitude: -71.5376, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Montpelier', state: 'VT', country: 'US', latitude: 44.2601, longitude: -72.5754, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Augusta', state: 'ME', country: 'US', latitude: 44.3666, longitude: -69.7843, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Harrisburg', state: 'PA', country: 'US', latitude: 40.2732, longitude: -76.8867, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Annapolis', state: 'MD', country: 'US', latitude: 38.9784, longitude: -76.4922, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Lansing', state: 'MI', country: 'US', latitude: 42.7325, longitude: -84.5555, timezone: 'America/Detroit', tzOffset: -5 },
  { city: 'Bismarck', state: 'ND', country: 'US', latitude: 46.8083, longitude: -100.7837, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Pierre', state: 'SD', country: 'US', latitude: 44.3683, longitude: -100.351, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Jefferson City', state: 'MO', country: 'US', latitude: 38.5767, longitude: -92.1735, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Baton Rouge', state: 'LA', country: 'US', latitude: 30.4515, longitude: -91.1871, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Helena', state: 'MT', country: 'US', latitude: 46.5891, longitude: -112.0361, timezone: 'America/Denver', tzOffset: -7 },

  // ===== United States - Additional major cities =====
  { city: 'Reno', state: 'NV', country: 'US', latitude: 39.5296, longitude: -119.8138, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Glendale', state: 'AZ', country: 'US', latitude: 33.5387, longitude: -112.185, timezone: 'America/Phoenix', tzOffset: -7 },
  { city: 'Scottsdale', state: 'AZ', country: 'US', latitude: 33.4942, longitude: -111.9261, timezone: 'America/Phoenix', tzOffset: -7 },
  { city: 'Chandler', state: 'AZ', country: 'US', latitude: 33.3062, longitude: -111.8413, timezone: 'America/Phoenix', tzOffset: -7 },
  { city: 'Gilbert', state: 'AZ', country: 'US', latitude: 33.3528, longitude: -111.789, timezone: 'America/Phoenix', tzOffset: -7 },
  { city: 'Plano', state: 'TX', country: 'US', latitude: 33.0198, longitude: -96.6989, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Garland', state: 'TX', country: 'US', latitude: 32.9126, longitude: -96.6389, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Frisco', state: 'TX', country: 'US', latitude: 33.1507, longitude: -96.8236, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Lubbock', state: 'TX', country: 'US', latitude: 33.5779, longitude: -101.8552, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Amarillo', state: 'TX', country: 'US', latitude: 35.222, longitude: -101.8313, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'El Paso', state: 'TX', country: 'US', latitude: 31.7619, longitude: -106.485, timezone: 'America/Denver', tzOffset: -7 },
  { city: 'Spokane', state: 'WA', country: 'US', latitude: 47.6588, longitude: -117.426, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Tacoma', state: 'WA', country: 'US', latitude: 47.2529, longitude: -122.4443, timezone: 'America/Los_Angeles', tzOffset: -8 },
  { city: 'Fort Wayne', state: 'IN', country: 'US', latitude: 41.0793, longitude: -85.1394, timezone: 'America/Indiana/Indianapolis', tzOffset: -5 },
  { city: 'Fayetteville', state: 'AR', country: 'US', latitude: 36.0657, longitude: -94.1574, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Shreveport', state: 'LA', country: 'US', latitude: 32.5251, longitude: -93.7502, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Mobile', state: 'AL', country: 'US', latitude: 30.6954, longitude: -88.0399, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Huntsville', state: 'AL', country: 'US', latitude: 34.7304, longitude: -86.5861, timezone: 'America/Chicago', tzOffset: -6 },
  { city: 'Tallahassee', state: 'FL', country: 'US', latitude: 30.4383, longitude: -84.2807, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Hialeah', state: 'FL', country: 'US', latitude: 25.8576, longitude: -80.2784, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Tampa', state: 'FL', country: 'US', latitude: 27.9506, longitude: -82.4572, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Toledo', state: 'OH', country: 'US', latitude: 41.6528, longitude: -83.5379, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Akron', state: 'OH', country: 'US', latitude: 41.0814, longitude: -81.519, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Dayton', state: 'OH', country: 'US', latitude: 39.7589, longitude: -84.1916, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Winston-Salem', state: 'NC', country: 'US', latitude: 36.0999, longitude: -80.2442, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Greensboro', state: 'NC', country: 'US', latitude: 36.1627, longitude: -79.792, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Durham', state: 'NC', country: 'US', latitude: 35.994, longitude: -78.8986, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Chesapeake', state: 'VA', country: 'US', latitude: 36.7682, longitude: -76.2875, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Norfolk', state: 'VA', country: 'US', latitude: 36.8508, longitude: -76.2859, timezone: 'America/New_York', tzOffset: -5 },
  { city: 'Baton Rouge', state: 'LA', country: 'US', latitude: 30.4515, longitude: -91.1871, timezone: 'America/Chicago', tzOffset: -6 },

  // ===== Canada - Major cities =====
  { city: 'Toronto', state: 'ON', country: 'CA', latitude: 43.6532, longitude: -79.3832, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Montreal', state: 'QC', country: 'CA', latitude: 45.5017, longitude: -73.5673, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Vancouver', state: 'BC', country: 'CA', latitude: 49.2827, longitude: -123.1207, timezone: 'America/Vancouver', tzOffset: -8 },
  { city: 'Calgary', state: 'AB', country: 'CA', latitude: 51.0447, longitude: -114.0719, timezone: 'America/Edmonton', tzOffset: -7 },
  { city: 'Edmonton', state: 'AB', country: 'CA', latitude: 53.5461, longitude: -113.4938, timezone: 'America/Edmonton', tzOffset: -7 },
  { city: 'Ottawa', state: 'ON', country: 'CA', latitude: 45.4215, longitude: -75.6972, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Winnipeg', state: 'MB', country: 'CA', latitude: 49.8951, longitude: -97.1384, timezone: 'America/Winnipeg', tzOffset: -6 },
  { city: 'Quebec City', state: 'QC', country: 'CA', latitude: 46.8139, longitude: -71.208, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Hamilton', state: 'ON', country: 'CA', latitude: 43.2557, longitude: -79.8711, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Kitchener', state: 'ON', country: 'CA', latitude: 43.4516, longitude: -80.4925, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'London', state: 'ON', country: 'CA', latitude: 42.9849, longitude: -81.2453, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Victoria', state: 'BC', country: 'CA', latitude: 48.4284, longitude: -123.3656, timezone: 'America/Vancouver', tzOffset: -8 },
  { city: 'Halifax', state: 'NS', country: 'CA', latitude: 44.6488, longitude: -63.5752, timezone: 'America/Halifax', tzOffset: -4 },
  { city: 'Saskatoon', state: 'SK', country: 'CA', latitude: 52.1332, longitude: -106.67, timezone: 'America/Regina', tzOffset: -6 },
  { city: 'Regina', state: 'SK', country: 'CA', latitude: 50.4455, longitude: -104.6186, timezone: 'America/Regina', tzOffset: -6 },
  { city: "St. John's", state: 'NL', country: 'CA', latitude: 47.5615, longitude: -52.7126, timezone: 'America/St_Johns', tzOffset: -3.5 },
  { city: 'Charlottetown', state: 'PE', country: 'CA', latitude: 46.2382, longitude: -63.1311, timezone: 'America/Halifax', tzOffset: -4 },
  { city: 'Fredericton', state: 'NB', country: 'CA', latitude: 45.9636, longitude: -66.6431, timezone: 'America/Moncton', tzOffset: -4 },
  { city: 'Moncton', state: 'NB', country: 'CA', latitude: 46.0853, longitude: -64.8026, timezone: 'America/Moncton', tzOffset: -4 },
  { city: 'Thunder Bay', state: 'ON', country: 'CA', latitude: 48.3809, longitude: -89.2477, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Windsor', state: 'ON', country: 'CA', latitude: 42.3149, longitude: -83.0364, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Kingston', state: 'ON', country: 'CA', latitude: 44.2312, longitude: -76.486, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Barrie', state: 'ON', country: 'CA', latitude: 44.3894, longitude: -79.6903, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Kelowna', state: 'BC', country: 'CA', latitude: 49.888, longitude: -119.496, timezone: 'America/Vancouver', tzOffset: -8 },
  { city: 'Abbotsford', state: 'BC', country: 'CA', latitude: 49.0504, longitude: -122.3045, timezone: 'America/Vancouver', tzOffset: -8 },
  { city: 'Sherbrooke', state: 'QC', country: 'CA', latitude: 45.4012, longitude: -71.8826, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Trois-Rivières', state: 'QC', country: 'CA', latitude: 46.3432, longitude: -72.542, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Saguenay', state: 'QC', country: 'CA', latitude: 48.4286, longitude: -71.0677, timezone: 'America/Toronto', tzOffset: -5 },
  { city: 'Lethbridge', state: 'AB', country: 'CA', latitude: 49.6934, longitude: -112.8442, timezone: 'America/Edmonton', tzOffset: -7 },
  { city: 'Red Deer', state: 'AB', country: 'CA', latitude: 52.2681, longitude: -113.8112, timezone: 'America/Edmonton', tzOffset: -7 },
  { city: 'Medicine Hat', state: 'AB', country: 'CA', latitude: 50.05, longitude: -110.7167, timezone: 'America/Edmonton', tzOffset: -7 },
  { city: 'Prince George', state: 'BC', country: 'CA', latitude: 53.9171, longitude: -122.7497, timezone: 'America/Vancouver', tzOffset: -8 },
  { city: 'Whitehorse', state: 'YT', country: 'CA', latitude: 60.7212, longitude: -135.0568, timezone: 'America/Whitehorse', tzOffset: -7 },
  { city: 'Yellowknife', state: 'NT', country: 'CA', latitude: 62.454, longitude: -114.3718, timezone: 'America/Yellowknife', tzOffset: -7 },
  { city: 'Iqaluit', state: 'NU', country: 'CA', latitude: 63.7467, longitude: -68.517, timezone: 'America/Iqaluit', tzOffset: -5 },
];

// Search cities by partial city name (case-insensitive) or state abbreviation.
// Returns up to 10 results.
export function searchCities(query: string): CityCoordinate[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const results = cityList.filter((c) => {
    const cityMatch = c.city.toLowerCase().includes(q);
    const stateMatch =
      c.state.toLowerCase() === q || c.state.toLowerCase().includes(q);
    return cityMatch || stateMatch;
  });

  return results.slice(0, 10);
}
